spring:
  datasource:
    #url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:./h2db
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
    #schema: classpath:sql/schema.sql
    initializationMode: always
