# docker-compose version
# docker-compose -f ./mysql-compose.yml down
# docker-compose -f ./mysql-compose.yml up -d
# docker exec -it mysql-javaspring-tutorials mysql -p
version: '3.8'
services:
  db:
    image: mysql:8.0.31
    container_name: mysql-javaspring-tutorials
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: Abc123456789
    ports:
      - 3310:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local